### ISSUE TITLE
Problems with alt_ids in HPO

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#7947]
Examining the HPO obo file we see there are cases where one term has been merged into another:

```yaml
id: HP:0030051
name: Tip-toe gait
alt_id: HP:0002394
alt_id: HP:0040083
def: "An abnormal gait pattern characterized by the failure of the heel to contact the floor at the onset of stance during gait." [PMID:24757457, PMID:26709689]
comment: Tip-toe walking (or simply toe-walking) is common in healthy young children, and should resolve spontaneously by 3 years of age. After this age, tip-toe gait must be differentiated from habitual toe gait, congenital short tendo calcaneus, cerebral palsy, syringomyelia, spinal tumor, hematoma in a lower limb muscle, or neuromuscular diseases like muscular dystrophy, Charcot-Marie-Tooth disease and hereditary sensorimotor neuropathies. If the toe gait persists for 2-3 years, this gait pattern is not considered to be habitual. Therefore, the judgment of habitual toe gait should not be determined without evaluation for other diseases.
synonym: "Tiptoe gait" EXACT []
synonym: "Toe walking" EXACT layperson []
synonym: "Walking on tiptoes" EXACT layperson []
xref: UMLS:C1843570
is_a: HP:0001288 ! Gait disturbance
```

this is telling us that both HP:0002394 and HP:0040083 were merged into HP:0030051

When looking at the RDF/OWL level, we would expect to see explicit URIs for the merged entities

However, only one of the above has an entry

 - http://purl.obolibrary.org/obo/HP_0040083 - a class with an obsolete record
 - http://purl.obolibrary.org/obo/HP_0002394 - no entry

this can be confirmed:

```
curl -L -s $OBO/hp.owl | grep HP_0002394
```

yields no results (the IRI is not present, only the alt_id CURIE annotation)

It looks like the HPO process for merging terms is to:

1. delete the class being merged
2. create an oboInOwl:hasAlternativeId annotation on the target class

I would recommend against this practice and instead use the standard protege obsoletion workflow

I think there needs to be a repair operation where we insert into the OWL file IRIs for HP_0002394 and other alt_id targets, and create an SOP moving forward
